config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users
  
  get "countries/:country_id/provinces" => "application#provinces", :as => "provinces", :format => :json
  get "provinces/:province_id/cities" => "application#cities", :as => "cities", :format => :json

  root to: 'static_pages#home', via: :get
  
  match '/help',      to: 'static_pages#help', via: :get
  match '/about',     to: 'static_pages#about', via: :get
  match '/contact',   to: 'static_pages#contact', via: :get
  
  match '/commerces_followed',   to: 'static_pages#commerces_followed', via: :get
  match '/my_orders',   to: 'static_pages#my_orders', via: :get
  match '/my_bookings',   to: 'static_pages#my_bookings', via: :get
  
  match '/bookings',   to: 'static_pages#bookings', via: :get
  
  match '/commerce_reviews',   to: 'static_pages#commerce_reviews', via: :get
  match '/commerce_bookings',   to: 'static_pages#commerce_bookings', via: :get
  match '/commerce_followers',   to: 'static_pages#commerce_followers', via: :get
  match '/commerce_admin',   to: 'static_pages#commerce_admin', via: :get

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :friendships, only: [:index, :create, :destroy]
  get 'friendship/create'
  get 'friendship/destroy'
  
  resources :commerces
  match '/my_commerces', to: "commerces#my_commerces", via: :get
  resources :branches
  get '/branch/profile/:id' => "branches#profile", as: "branch_profile"
  resources :publications, only: [:create, :destroy]
  
  resources :menus
  resources :items
  
  resource :cart, only: [:show]
  resource :order, only: [:update]
  resources :orders, only: [:index]
  resources :order_lines, only: [:create, :update, :destroy]
  
  match '/accept_request', to: "friendships#accept_request", via: :post
  match '/cancel_request', to: "friendships#cancel_request", via: :post
  match '/unfriend', to: "friendships#unfriend", via: :post
  
  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  belongs_to :branch
  belongs_to :user
  
  validates :branch, uniqueness: { scope: :user }
  
  accepts_nested_attributes_for :user
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :commerce
  belongs_to :city
  belongs_to :menu
  
  has_many :administrators
  has_many :users, through: :administrator
  
  has_many :publications, dependent: :destroy
  has_many :items
  
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :commerce }
  validates :address, presence: true
  validates :phone, presence: true
  validates :city, presence: true
  
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :administrators
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province
  
  has_many :branches
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/commerce.rb
class Commerce < ActiveRecord::Base
  has_many :branches
  belongs_to :user
  
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :user, presence: true
  
  accepts_nested_attributes_for :branches, allow_destroy: true
  
  acts_as_taggable
  acts_as_taggable_on :categories
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :provinces
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  
  validates :user, uniqueness: { scope: :friend }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :branch
  has_many :order_lines
  
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :branch }
  validates :description, presence: true
  validates :price, presence: true
  validates :branch, presence: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope { order('microposts.created_at DESC')}
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :branch
  has_many :order_lines
  
#  validates :user, presence: true
#  validates :branch, presence: true
#  validates :address, presence: true
#  validates :phone, presence: true
#  validates :cash, presence: true, numericality: { greater_than: 0 }
#  validates :shipping_cost, presence: true, numericality: { greater_than_or_equal_to: 0 }
#  validates :status, presence: true
  
  before_create :set_order_status
  before_save :update_subtotal
  
  def subtotal
    order_lines.collect { |ol| ol.valid? ? (ol.quantity * ol.unit_price) : 0 }.sum
  end
  
  private
  
  def set_order_status
    self.status = "En progreso"
  end
  
  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :item

  validates :order, presence: true
  validates :item, presence: true
#  validates :unit_price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
#  validates :amount, presence: true, numericality: { greater_than: 0 }
  
  before_save :finalize
  
  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end
  
  def total_price
    unit_price * quantity
  end
  
private
  
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end
  
  def finalize
    self[:unit_price] = unit_price
    self[:amount] = quantity * self[:unit_price]
  end
  
end

app/models/province.rb
class Province < ActiveRecord::Base
  belongs_to :country
  has_many :cities
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :branch
  
  validates :branch_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope { order('publications.created_at DESC')}
end

app/models/sex.rb
class Sex < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :commerces
  has_many :administrators
  has_many :branches, through: :administrator
  belongs_to :sex
  
  
  has_many :friendships
  has_many :friends, -> { where("status == 'accepted'")}, through: :friendships
  
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, -> { where("status == 'accepted'")}, through: :inverse_friendships, source: :user
  
  has_many :friendship_requests, class_name: "Friendship", foreign_key: "friend_id"
  has_many :requests, -> { where("status == 'pending'")}, through: :friendship_requests, source: :user
  
  has_many :sent_requests, class_name: "Friendship", foreign_key: "user_id"
  has_many :sents, -> { where("status == 'pending'")}, through: :sent_requests, source: :friend
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
           
  validates_confirmation_of :password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :sex, presence: true
  
  before_save :set_profile_picture
  
  def name
    self[:first_name] + ' ' + self[:last_name]
  end
  
  private
  
  def set_profile_picture
    if self[:photo_url].empty?
      if self[:sex_id] == 1
        self[:photo_url] = "/img/signup_male.jpg"
      else
        self[:photo_url] = "/img/signup_female.png"
      end
    end
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/commerce_helper.rb
module CommerceHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/shared/_bookings.html.erb
<div class="panel panel-primary">
	<div class="panel-heading" align="center"><strong>Reservas On-line</strong></div>
	<div class="panel-body" align="center">
		<% if true %>
			<p>No implementado.</p>
		<% else %>
			<p>No tiene pedidos nuevos.</p>
		<% end %>
	</div>
</div>

app/views/shared/_branch_info.html.erb
<%
	@branch = Branch.find_by_id(session[:branch_id])
	commerce_name = @branch.commerce.name
	name = @branch.name
	city = @branch.city.name
	province = @branch.city.province.name
	country = @branch.city.province.country.name
	address = @branch.address
	phone = @branch.phone
%>
<div id="info_branch">
	<div class="panel panel-default">
	  <div class="panel-heading" id="branch-panel-heading"><h3 class="panel-title">Información</h3></div>
	  <div class="panel-body" id="branch-panel-body">
	  	<table>
	  		<tr>
	  			<td>Comercio: </td> <td><strong><%= commerce_name %></strong></td>
	  		</tr>
	  		<tr>
	  			<td>Local: </td> <td><strong><%= name %></strong></td>
	  		</tr>
	  		<tr>
	  			<td>Ubicación: </td> <td><strong><%= city + ', ' + province + ', ' + country %></strong></td>
	  		</tr>
	  		<tr>
	  			<td>Dirección: </td> <td><strong><%= address %></strong></td>
	  		</tr>
	  		<tr>
	  			<td>Teléfono: </td> <td><strong><%= phone %></strong></td>
	  		</tr>
	  	</table>
	  </div>
	</div>
</div>
 

app/views/shared/_item_branch.html.erb
<div id="<%= "popup-item-" + item.id.to_s %>" class="white-popup mfp-hide">
  <%= render layout: 'items/view', locals: {item: item} {} %>
</div>



<div class="col-xs-6 col-sm-6 col-md-6">
	<div class="well">
		<div class="media">
			<div class="media-left">
				<a href="<%= "#popup-item-" + item.id.to_s %>" class="open-popup-link">
					<img class="media-object" src="<%= item.photo %>" alt="<%= item.name %>" width="100px" height="100px">
				</a>
			</div>
			<div class="media-body">
				<h4 class="media-heading"><%= item.name %></h4>
				<%= item.description %>
			</div>
			<div class="item-bottom">
				<div class="links-branch">
					<% if user_signed_in? %>
						<% if action_name == "edit" %>
							<%= link_to "Eliminar", item_path(item.id), method: :delete, data: { confirm: "¿Está segurro de eliminar este item?" } %> 
								| <%= link_to "Editar", edit_item_path(item.id) %> | <a href="<%= "#popup-item-" + item.id.to_s %>" class="open-popup-link">Ver</a>
							<h4 class="text-right">Precio: <span style="color: green"><%= number_to_currency item.price %></span></h4>
						<% else %>
						      <h4 class="text-right">Precio: <span style="color: green"><%= number_to_currency item.price %></span></h4>
						      <%= link_to '¡Pedir Ahora!', "#new_order_line_modal_#{item.id}", 'data-toggle' => 'modal', class: "btn btn-primary" %>
						      	<div class="modal fade" id="new_order_line_modal_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								  <div class="modal-dialog">
								    <div class="modal-content">
								      <div class="modal-header">
								        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								        <h4 class="modal-title" id="myModalLabel">Agregar item</h4>
								      </div>
								      <div class="modal-body">
								        <%= render 'items/form_request', modal: true, item: item %>
								      </div>
								      <div class="modal-footer">
								        <button type="button" class="btn btn-default" data-dismiss="modal" id="closeModal_<%= item.id %>">Cerrar</button>
								      </div>
								    </div>
								  </div>
								</div>
						<% end %>
					<% end %>
				</div> 
			</div>
		</div>
	</div>
</div>

app/views/shared/_micropost_form.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<%= form_for(@micropost) do |f| %>
			<div class="form-group">
				<%= f.text_field :content, class: "form-control", placeholder: "¿Qué estas pensando?",
									autocomplete: "off" %>
			</div>
			<div align="right">
				<%= f.submit "Publicar", class:"btn btn-primary" %>
			</div>
		<% end %>
 	</div>
</div>

app/views/shared/_orders.html.erb
<div class="panel panel-primary">
	<div class="panel-heading" align="center"><strong>Pedidos On-line</strong></div>
	<div class="panel-body" align="center">
		<% if orders > 0 %>
			<h3>¡Atención!</h3>
			<p>¡Tiene <strong><%= orders %></strong> pedidos nuevos! <%= link_to "Atender ahora", orders_path %></a></p>
		<% else %>
			<p>No tiene pedidos nuevos.</p>
		<% end %>
	</div>
</div>

app/views/shared/_pending_requests.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Solicitudes pendientes</div>
	<div class="panel-body">
		<% count = @friendship_requests.count %>
		<% if count > 0 %>
			<div id="requestsCarousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  	<% for i in 0..(count-1) %>
			  		<li data-target="#requestsCarousel" data-slide-to="<%= i %>" class="<%= (i == 0) ? 'active' : ' ' %>"></li>
			  	<% end %>
			  </ol>
			
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
				<% @friendship_requests.each do |user| %>
				    <div class="<%= user == @friendship_requests.first ? 'item active' : 'item' %>">
				      	<div class="media">
						  <div class="media-left media-middle">
						    <a href="#">
						      <img class="media-object" src="<%= user.photo_url %>" alt="Foto de perfil" width="64px" height="64px">
						    </a>
						  </div>
						  <div class="media-body">
						    <h4 class="media-heading"><%= user.first_name + ' ' + user.last_name %></h4>
						    <p><%= link_to "Aceptar", accept_request_path(friend_id: user), method: :post %> | <%= link_to "Rechazar", cancel_request_path(friend_id: user), method: :post %></p>
						  </div>
						</div>
				    </div>
				<% end %>
			  </div>
			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#requestsCarousel" role="button" data-slide="prev">
			    <
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#requestsCarousel" role="button" data-slide="next">
			    >
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		<% else %>
			<p> No existen solicitudes pendientes </p>
		<% end %>	
	</div>
</div>

app/views/shared/_publication_form.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<%= form_for(@publication) do |f| %>
			<div class="form-group">
				<%= f.text_field :content, class: "form-control", placeholder: "Comparte algo...",
									autocomplete: "off" %>
			</div>
			<div align="right">
				<%= f.submit "Publicar", class:"btn btn-primary" %>
			</div>
		<% end %>
 	</div>
</div>

app/views/shared/_reviews.html.erb
<div class="panel panel-primary">
	<div class="panel-heading" align="center"><strong>Opiniones</strong></div>
	<div class="panel-body" align="center">
		<% if true %>
			<p>No implementado.</p>
		<% else %>
			<p>No tiene pedidos nuevos.</p>
		<% end %>
	</div>
</div>

app/views/shared/_sent_requests.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Solicitudes enviadas</div>
	<div class="panel-body">
		<% count = @sent_requests.count %>
		<% if count > 0 %>
		<div id="sentsCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		  	<% for i in 0..(count-1) %>
		  		<li data-target="#sentsCarousel" data-slide-to="<%= i %>" class="<%= (i == 0) ? 'active' : ' ' %>"></li>
		  	<% end %>
		  </ol>
		
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
			<% @sent_requests.each do |user| %>
			    <div class="<%= user == @sent_requests.first ? 'item active' : 'item' %>">
			      <div class="media">
					  <div class="media-left media-middle">
					    <a href="#">
					      <img class="media-object" src="<%= user.photo_url %>" alt="Foto de perfil" width="64px" height="64px">
					    </a>
					  </div>
					  <div class="media-body">
					    <h4 class="media-heading"><%= user.first_name + ' ' + user.last_name %></h4>
					    <p><%= link_to "Cancelar", cancel_request_path(friend_id: user), method: :post %></p>
					  </div>
					</div>
			    </div>
			<% end %>
		  </div>
		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#sentsCarousel" role="button" data-slide="prev">
		    <
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#sentsCarousel" role="button" data-slide="next">
		    >
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		<% else %>
			<p>No existen solicitudes enviadas</p>
		<% end %>
	 </div>
</div>

app/views/shared/_suggested_commerces.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Comercios sugeridos</div>
	<div class="panel-body">
		<% count = @commerces.count %>
		<% if count > 0 %>
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		  	<% for i in 0..(count-1) %>
		    	<li data-target="#myCarousel" data-slide-to="<%= i %>" class="<%= (i == 0) ? 'active' : ' ' %>"></li>
		  	<% end %>
		  </ol>
		
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
			<% @commerces.each do |commerce| %>
			    <div class="<%= commerce == @commerces.first ? 'item active' : 'item' %>">
			      <div class="media">
					  <div class="media-left media-middle">
					    <a href="#">
					      <img class="media-object" src="<%= commerce.branches.first.photo_url %>" alt="Foto de perfil" width="64px" height="64px">
					    </a>
					  </div>
					  <div class="media-body">
					    <h4 class="media-heading"><%= commerce.name  %></h4>
					    <p><%= link_to "Ver", commerce_path(commerce.id) %></p>
					  </div>
					</div>
			    </div>
			<% end %>
		  </div>
		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		    <
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		    >
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		<% else %>
			<p>No existen comercios sugeridos</p>
		<% end %>
	</div>
</div>

app/views/shared/_suggested_friends.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">Personas que quizás conozcas</div>
	<div class="panel-body">
		<% count = @users.count %>
		<% if count > 0 %>
		<div id="friendCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		  	<% for i in 0..(count-1) %>
		    	<li data-target="#friendCarousel" data-slide-to="<%= i %>" class="<%= (i == 0) ? 'active' : ' ' %>"></li>
		  	<% end %>
		  </ol>
		
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
			<% @users.each do |user| %>
			    <div class="<%= user == @users.first ? 'item active' : 'item' %>">
			      <div class="media">
					  <div class="media-left media-middle">
					    <a href="#">
					      <img class="media-object" src="<%= user.photo_url %>" alt="Foto de perfil" width="64px" height="64px">
					    </a>
					  </div>
					  <div class="media-body">
					    <h4 class="media-heading"><%= user.first_name + ' ' + user.last_name %></h4>
					    <p><%= link_to "Agregar", friendships_path(friend_id: user), method: :post %></p>
					  </div>
					</div>
			    </div>
			<% end %>
		  </div>
		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#friendCarousel" role="button" data-slide="prev">
		    <
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#friendCarousel" role="button" data-slide="next">
		    >
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		<% else %>
			<p>No existen personas sugeridas</p>
		<% end %>
	</div>
</div>