config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users
  
  get "countries/:country_id/provinces" => "application#provinces", :as => "provinces", :format => :json
  get "provinces/:province_id/cities" => "application#cities", :as => "cities", :format => :json

  root to: 'static_pages#home', via: :get
  
  match '/help',      to: 'static_pages#help', via: :get
  match '/about',     to: 'static_pages#about', via: :get
  match '/contact',   to: 'static_pages#contact', via: :get
  
  match '/commerces_followed',   to: 'static_pages#commerces_followed', via: :get
  match '/my_orders',   to: 'static_pages#my_orders', via: :get
  match '/my_bookings',   to: 'static_pages#my_bookings', via: :get
  
  match '/bookings',   to: 'static_pages#bookings', via: :get
  
  match '/commerce_reviews',   to: 'static_pages#commerce_reviews', via: :get
  match '/commerce_bookings',   to: 'static_pages#commerce_bookings', via: :get
  match '/commerce_followers',   to: 'static_pages#commerce_followers', via: :get
  match '/commerce_admin',   to: 'static_pages#commerce_admin', via: :get

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :friendships, only: [:index, :create, :destroy]
  get 'friendship/create'
  get 'friendship/destroy'
  
  resources :commerces
  match '/my_commerces', to: "commerces#my_commerces", via: :get
  resources :branches
  get '/branch/profile/:id' => "branches#profile", as: "branch_profile"
  resources :publications, only: [:create, :destroy]
  
  resources :menus
  resources :items
  
  resource :cart, only: [:show]
  resource :order, only: [:update]
  resources :orders, only: [:index]
  resources :order_lines, only: [:create, :update, :destroy]
  
  match '/accept_request', to: "friendships#accept_request", via: :post
  match '/cancel_request', to: "friendships#cancel_request", via: :post
  match '/unfriend', to: "friendships#unfriend", via: :post
  
  

end

app/models/commerce.rb
class Commerce < ActiveRecord::Base
  has_many :branches
  belongs_to :user
  
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :user, presence: true
  
  accepts_nested_attributes_for :branches, allow_destroy: true
  
  acts_as_taggable
  acts_as_taggable_on :categories
end

app/controllers/commerces_controller.rb
#encoding: utf-8
class CommercesController < ApplicationController
  before_action :set_commerce, only: [:show, :edit, :update]
  before_filter :sanitize_page_params, only: [:create]
  before_filter :authenticate_user!, only: [:new, :edit, :destroy, :create, :update]
  before_filter :verificate_user, only: [:update]
  before_filter :check_for_cancel, only: [:create, :update]
  
  def index
    @commerces = Commerce.all.order(:name)
  end
  
  def show
    session[:commerce_id] = @commerce.id if @commerce
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @commerce.update(commerce_params)
        format.html { redirect_to my_commerces_path, notice: 'Comercio actualizado correctamente' }
      else
        format.html { render :edit, alert: 'No se pudo actualizar el comercio' }
      end
    end
  end
  
  def new
    @commerce = Commerce.new
  end
  
  def create
    @commerce = Commerce.new(commerce_params)
    @commerce.user = current_user
    @commerce.branches.build
    @commerce.branches.first.name = params[:commerce][:branches][:name]
    @commerce.branches.first.city = params[:commerce][:branches][:city]
    @commerce.branches.first.address = params[:commerce][:branches][:address]
    @commerce.branches.first.phone = params[:commerce][:branches][:phone]
    
    respond_to do |format|
      if @commerce.save
        format.html { redirect_to my_commerces_path, notice: 'Comercio creado correctamente' }
      else
        format.html { render :new, alert: 'No se pudo crear el commercio' }
      end
    end
  end
  
  def my_commerces
    commerces = Commerce.all
    @my_commerces = Array.new
    commerces.each do |com|
      if com.user_id == current_user.id
        @my_commerces << com
      end
    end
  end
  
  private
  
  def set_commerce
    @commerce = Commerce.find_by_id(params[:id])
  end
  
  def commerce_params
    params.require(:commerce).permit(:name, :user, :tag_list, branches_attributes: [:name, :address, :phone, :type, :city, :photo_url])
  end
  
  def sanitize_page_params
    id = params[:commerce][:branches][:city].to_i
    params[:commerce][:branches][:city] = City.find_by_id(id)
  end
  
  def verificate_user
    commerce = Commerce.find_by_id(params[:id])
    if commerce.user != current_user
      redirect_to root_path, alert: 'No tiene permisos para realizar esta acción'
    end
  end
  
  def check_for_cancel
    if params[:commit] == "Cancelar"
      redirect_to my_commerces_path
    end
  end
end

app/helpers/commerce_helper.rb
module CommerceHelper
end

app/views/commerces/_form.html.erb
<%= form_for :commerce, url: commerces_path do |f| %>
	<% if @commerce.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@commerce.errors.count, "error") %> prohibited this commerce from being saved:</h2>
		
		  <% @commerce.errors.full_messages.each do |message| %>
		    <div class="alert alert-danger" role="alert">
		    	<p><%= message %></p>
		    </div>
		  <% end %>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label "Nombre del Comercio" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label "Categorías" %>
		<%= f.text_field :tag_list, class: "form-control" %>
	</div>
	
	<!-- Registrar Sucursal Principal -->
	<div class="panel panel-default">
		<div class="panel-heading">Sucursal Principal</div>
		<div class="panel-body">
			<%= f.fields_for :branches do |branch| %>
				<%= render 'branches/branch_fields', field: branch %>
			<% end %>
		</div>
		<!-- Registrar Administradores de la Sucursal Principal -->
		<div class="panel panel-default">
			<div class="panel-heading">Administradores</div>
			<div class="panel-body">
				<%= f.fields_for :administrators do |admin| %>
					<%= render 'administrators/administrator_fields', field: admin %>
				<% end %>
			</div>
		</div>
	</div>
	
	<div class="actions">
		<%= f.submit "Guardar", class: "btn btn-primary" %>
		<%= f.submit "Cancelar", class: "btn btn-danger" %>
	</div>
<% end %>

app/views/commerces/_form_edit.html.erb
<%= form_for @commerce do |f| %>
	<% if @commerce.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@commerce.errors.count, "error") %> prohibited this commerce from being saved:</h2>
		
		  <% @commerce.errors.full_messages.each do |message| %>
		    <div class="alert alert-danger" role="alert">
		    	<p><%= message %></p>
		    </div>
		  <% end %>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label "Nombre del Comercio" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label "Categorías" %>
		<%= f.text_field :tag_list, class: "form-control" %>
	</div>
	
	<div class="actions">
		<%= f.submit "Guardar", class: "btn btn-primary" %>
		<%= f.submit "Cancelar", class: "btn btn-danger" %>
	</div>
<% end %>
<br />
	<div class="panel panel-default">
	  <div class="panel-heading">Sucursales</div>
	
	  <!-- Table -->
	  <table class="table">
	    <thead>
	    	<th>Nombre</th>
	    	<th>Ciudad</th>
	    	<th>Dirección</th>
	    	<th>Teléfono</th>
	    </thead>
	    <tbody>
	    	<% @commerce.branches.each do |branch| %>
	    		<tr>
	    			<td><%= branch.name %></td>
	    			<td><%= branch.city.name %></td>
	    			<td><%= branch.address %></td>
	    			<td><%= branch.phone %></td>
	    		</tr>
	    	<% end %>
	    </tbody>
	  </table>
	</div>

app/views/commerces/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Editar Comercio</h4>
  </div>
  <div class="panel-body">
  	<%= render 'form_edit' %>
  </div>
</div>

app/views/commerces/index.html.erb
<div class="page-header">
  <h1>Comercios adheridos</h1>
</div>
<% if not @commerces.nil? %>
	<div class="col-xs-12 col-sm-6 col-md-8">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Comercios</div>
					
			<!-- Table -->
			<table class="table">
				<thead>
					<tr>
						<th>Comercio</th>
						<th>Sucursal</th>
						<th>Provincia</th>
						<th>Ciudad</th>
					</tr>
				</thead>
				<tbody>
					<% @commerces.each do |com| %>
						<% com.branches.each do |branch| %>
							<tr>
								<td><%= link_to com.name, commerce_path(com.id) %></td>
								<td><%= link_to branch.name, branch_profile_path(branch.id) %></td>
								<td><%= branch.city.province.name %></td>
								<td><%= branch.city.name %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
<% end %>

app/views/commerces/my_commerces.html.erb
<div class="page-header">
  <h1>Mis comercios</h1>
</div>
<% if not @my_commerces.nil? %>
	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">
			<p>Aquí puede ver los comercios de los que usted es propietario.</p>	
		</div>
		<div class="panel-body" align="right">
			<%= button_to "Nuevo Comercio", new_commerce_path, type: "button", class: "btn btn-default", method: :get %>
		</div>
	
		<!-- Table -->
		<table class="table">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Sucursales</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @my_commerces.each do |com| %>
					<tr>
						<td><%= com.name %></td>
						<td><%= com.branches.count %></td>
						<td><%= link_to "Ver", commerce_path(com.id) %></td>
						<td><%= link_to "Editar", edit_commerce_path(com.id) %></td>
						<td><%= link_to "Eliminar", commerce_path(com.id) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% end %>

app/views/commerces/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Nuevo Comercio</h4>
    <p>Está por registrar un nuevo comercio a nombre de: <%= current_user.first_name + ' ' + current_user.last_name %></p>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>
</div>

app/views/commerces/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-8">
	<% if @commerce.nil? %>
		<p>Error. El comercio no existe</p>
	<% else %>
		<div class="page-header">
		  <h1><%= @commerce.name %></h1>
		</div>
		
			<div class="panel panel-primary">
			  <div class="panel-heading">Información Básica</div>
			  <div class="panel-body">
			  	<!-- Table -->
				<table class="table">
					<tr>
						<td class="col-md-4">Nombre</td>
						<td class="col-md-8"><%= @commerce.name %></td>
					</tr>
					<tr>
						<td class="col-md-4">Propietario</td>
						<td class="col-md-8"><%= @commerce.user.first_name + ' ' + @commerce.user.last_name %></td>
					</tr>
					<tr>
						<td class="col-md-4">Categorías</td>
						<td class="col-md-8"><%= @commerce.tag_list %></td>
					</tr>
				</table>
			  </div>
			</div>
			<div align="right">
				<%= button_to 'Nuevo Local', new_branch_path, method: :get, class: "btn btn-primary" if current_user == @commerce.user%><br />
			</div>
			<div class="panel panel-success">
			  <div class="panel-heading">Locales</div>
			  <div class="panel-body">
			  	<!-- Table -->
				<table class="table">
					<thead>
						<th>Nombre</th>
						<th>Dirección</th>
						<th>Teléfono</th>
						<th></th>
						<th></th>
						<th></th>
					</thead>
					<tbody>
						<% @commerce.branches.each do |branch| %>
							<tr>
								<td class="col-md-3"><%= branch.name %></td>
								<td class="col-md-3"><%= branch.address %></td>
								<td class="col-md-3"><%= branch.phone %></td>
								<td class="col-md-1"><%= link_to 'Ver', branch_profile_path(branch.id) %></td>
								<td class="col-md-1"><%= link_to 'Administrar', branch_path(branch.id) if current_user == @commerce.user%></td>
								<td class="col-md-1"><%= link_to 'Editar', edit_branch_path(branch.id) if current_user == @commerce.user%></td>
								<td class="col-md-1"><%= link_to 'Eliminar', '#' if current_user == @commerce.user%></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			  </div>
			</div>
	<% end %>
</div>