config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users
  
  get "countries/:country_id/provinces" => "application#provinces", :as => "provinces", :format => :json
  get "provinces/:province_id/cities" => "application#cities", :as => "cities", :format => :json

  root to: 'static_pages#home', via: :get
  
  match '/help',      to: 'static_pages#help', via: :get
  match '/about',     to: 'static_pages#about', via: :get
  match '/contact',   to: 'static_pages#contact', via: :get
  
  match '/commerces_followed',   to: 'static_pages#commerces_followed', via: :get
  match '/my_orders',   to: 'static_pages#my_orders', via: :get
  match '/my_bookings',   to: 'static_pages#my_bookings', via: :get
  
  match '/bookings',   to: 'static_pages#bookings', via: :get
  
  match '/commerce_reviews',   to: 'static_pages#commerce_reviews', via: :get
  match '/commerce_bookings',   to: 'static_pages#commerce_bookings', via: :get
  match '/commerce_followers',   to: 'static_pages#commerce_followers', via: :get
  match '/commerce_admin',   to: 'static_pages#commerce_admin', via: :get

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :friendships, only: [:index, :create, :destroy]
  get 'friendship/create'
  get 'friendship/destroy'
  
  resources :commerces
  match '/my_commerces', to: "commerces#my_commerces", via: :get
  resources :branches
  get '/branch/profile/:id' => "branches#profile", as: "branch_profile"
  resources :publications, only: [:create, :destroy]
  
  resources :menus
  resources :items
  
  resource :cart, only: [:show]
  resource :order, only: [:update]
  resources :orders, only: [:index]
  resources :order_lines, only: [:create, :update, :destroy]
  
  match '/accept_request', to: "friendships#accept_request", via: :post
  match '/cancel_request', to: "friendships#cancel_request", via: :post
  match '/unfriend', to: "friendships#unfriend", via: :post
  
  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  
  validates :user, uniqueness: { scope: :friend }
end

app/controllers/friendships_controller.rb
#encoding: utf-8
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id], status: 'pending')
    
    if @friendship.save
      flash[:notice] = "Solicitud enviada"
      redirect_to root_path
    else
      flash[:alert] = "No se pudo enviar la solicitud"
      redirect_to root_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Amigo quitado"
    redirect_to root_path
  end
  
  def index
    if user_signed_in?
      suggested_friends
      @friendship_requests = current_user.requests
      @friends = current_user.friends
      @friends += current_user.inverse_friends
      @sent_requests = current_user.sents
    end
  end
  
  def accept_request
    if user_signed_in?
      user = User.find_by_id(params[:friend_id])
      request = Friendship.find_by_user_id_and_friend_id(user, current_user)
      if request
        request.status = 'accepted'
        request.friends_since = Time.now
        request.save!
      else
        flash[:alert] = "No se pudo concretar la operacion"
      end
      redirect_to friendships_path
    end
  end
  
  def cancel_request
    if user_signed_in?
      user = User.find_by_id(params[:friend_id])
      request = Friendship.find_by_user_id_and_friend_id(user, current_user)
      if !request
        request = Friendship.find_by_user_id_and_friend_id(current_user, user)
      end
      if request.destroy!
        flash[:notice] = "Rechazado correctamente"
      else
        flash[:alert] = "No se pudo concretar la operacion"
      end
      redirect_to friendships_path
    end
  end
  
  def unfriend
    if user_signed_in?
      user = User.find_by_id(params[:friend_id])
      request = Friendship.find_by_user_id_and_friend_id(user, current_user)
      if !request
        request = Friendship.find_by_user_id_and_friend_id(current_user, user)
      end
      
      if request
        request.destroy!
        flash[:notice] = "Eliminado correctamente"
      else
        flash[:alert] = "No se pudo concretar la operacion"
      end
      redirect_to friendships_path
    end
  end
  
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/views/friendships/_display_friend.html.erb
<div class="col-xs-6 col-sm-6 col-md-6">
	<div class="well">
		<div class="media">
		  <div class="media-left media-middle">
		    <a href="#">
		      <img class="media-object" src="<%= friend.photo_url %>" alt="Foto de perfil" width="75">
		    </a>
		  </div>
		  <div class="media-body">
		    <h4 class="media-heading"><%= friend.name %></h4>
		    <p> 
		    	<%= link_to "Ver Perfil", "#" %>
		    <br />
		    	<%= link_to "Quitar", unfriend_path(friend_id: friend), method: :post, data: { confirm: '¿Está seguro de eliminar a este amigo?'} %>
		    </p>
		  </div>
		</div>
	</div>
</div>

app/views/friendships/create.html.erb
<h1>Friendship#create</h1>
<p>Find me in app/views/friendship/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendship#destroy</h1>
<p>Find me in app/views/friendship/destroy.html.erb</p>

app/views/friendships/index.html.erb
<%
	@tabs = Hash.new
	@tabs["friends"] = "active"
	@requests = !current_user.nil? ? current_user.requests.count : 0
%>
<% if user_signed_in? %>
	<%= render 'layouts/tabs_client' %>
	<div class="page-header">
	  <h1>Amigos</h1>
	</div>
	<div class="row">
	  <div class="col-xs-12 col-sm-6 col-md-8">
		<div class="row">
			<% @friends.each do |friend| %>
				<%= render layout: "display_friend", locals: { friend: friend } { } %>
			<% end %>
		</div>
	  </div>
	  <div class="col-xs-6 col-md-4">
	  	<%= render 'shared/pending_requests' %>
	  	
	  	<%= render 'shared/sent_requests' %>
	  	
	  	<%= render 'shared/suggested_friends' %>
	  </div>
	</div>
<% end %>

	