config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users
  
  get "countries/:country_id/provinces" => "application#provinces", :as => "provinces", :format => :json
  get "provinces/:province_id/cities" => "application#cities", :as => "cities", :format => :json

  root to: 'static_pages#home', via: :get
  
  match '/help',      to: 'static_pages#help', via: :get
  match '/about',     to: 'static_pages#about', via: :get
  match '/contact',   to: 'static_pages#contact', via: :get
  
  match '/commerces_followed',   to: 'static_pages#commerces_followed', via: :get
  match '/my_orders',   to: 'static_pages#my_orders', via: :get
  match '/my_bookings',   to: 'static_pages#my_bookings', via: :get
  
  match '/bookings',   to: 'static_pages#bookings', via: :get
  
  match '/commerce_reviews',   to: 'static_pages#commerce_reviews', via: :get
  match '/commerce_bookings',   to: 'static_pages#commerce_bookings', via: :get
  match '/commerce_followers',   to: 'static_pages#commerce_followers', via: :get
  match '/commerce_admin',   to: 'static_pages#commerce_admin', via: :get

  resources :users
  resources :microposts, only: [:create, :destroy]
  resources :friendships, only: [:index, :create, :destroy]
  get 'friendship/create'
  get 'friendship/destroy'
  
  resources :commerces
  match '/my_commerces', to: "commerces#my_commerces", via: :get
  resources :branches
  get '/branch/profile/:id' => "branches#profile", as: "branch_profile"
  resources :publications, only: [:create, :destroy]
  
  resources :menus
  resources :items
  
  resource :cart, only: [:show]
  resource :order, only: [:update]
  resources :orders, only: [:index]
  resources :order_lines, only: [:create, :update, :destroy]
  
  match '/accept_request', to: "friendships#accept_request", via: :post
  match '/cancel_request', to: "friendships#cancel_request", via: :post
  match '/unfriend', to: "friendships#unfriend", via: :post
  
  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  belongs_to :branch
  belongs_to :user
  
  validates :branch, uniqueness: { scope: :user }
  
  accepts_nested_attributes_for :user
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :commerce
  belongs_to :city
  belongs_to :menu
  
  has_many :administrators
  has_many :users, through: :administrator
  
  has_many :publications, dependent: :destroy
  has_many :items
  
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :commerce }
  validates :address, presence: true
  validates :phone, presence: true
  validates :city, presence: true
  
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :administrators
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province
  
  has_many :branches
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/commerce.rb
class Commerce < ActiveRecord::Base
  has_many :branches
  belongs_to :user
  
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :user, presence: true
  
  accepts_nested_attributes_for :branches, allow_destroy: true
  
  acts_as_taggable
  acts_as_taggable_on :categories
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :provinces
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  
  validates :user, uniqueness: { scope: :friend }
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :branch
  has_many :order_lines
  
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :branch }
  validates :description, presence: true
  validates :price, presence: true
  validates :branch, presence: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope { order('microposts.created_at DESC')}
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :branch
  has_many :order_lines
  
#  validates :user, presence: true
#  validates :branch, presence: true
#  validates :address, presence: true
#  validates :phone, presence: true
#  validates :cash, presence: true, numericality: { greater_than: 0 }
#  validates :shipping_cost, presence: true, numericality: { greater_than_or_equal_to: 0 }
#  validates :status, presence: true
  
  before_create :set_order_status
  before_save :update_subtotal
  
  def subtotal
    order_lines.collect { |ol| ol.valid? ? (ol.quantity * ol.unit_price) : 0 }.sum
  end
  
  private
  
  def set_order_status
    self.status = "En progreso"
  end
  
  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :item

  validates :order, presence: true
  validates :item, presence: true
#  validates :unit_price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
#  validates :amount, presence: true, numericality: { greater_than: 0 }
  
  before_save :finalize
  
  def unit_price
    if persisted?
      self[:unit_price]
    else
      item.price
    end
  end
  
  def total_price
    unit_price * quantity
  end
  
private
  
  def item_present
    if item.nil?
      errors.add(:item, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end
  
  def finalize
    self[:unit_price] = unit_price
    self[:amount] = quantity * self[:unit_price]
  end
  
end

app/models/province.rb
class Province < ActiveRecord::Base
  belongs_to :country
  has_many :cities
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :branch
  
  validates :branch_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope { order('publications.created_at DESC')}
end

app/models/sex.rb
class Sex < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :commerces
  has_many :administrators
  has_many :branches, through: :administrator
  belongs_to :sex
  
  
  has_many :friendships
  has_many :friends, -> { where("status == 'accepted'")}, through: :friendships
  
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, -> { where("status == 'accepted'")}, through: :inverse_friendships, source: :user
  
  has_many :friendship_requests, class_name: "Friendship", foreign_key: "friend_id"
  has_many :requests, -> { where("status == 'pending'")}, through: :friendship_requests, source: :user
  
  has_many :sent_requests, class_name: "Friendship", foreign_key: "user_id"
  has_many :sents, -> { where("status == 'pending'")}, through: :sent_requests, source: :friend
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
           
  validates_confirmation_of :password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :sex, presence: true
  
  before_save :set_profile_picture
  
  def name
    self[:first_name] + ' ' + self[:last_name]
  end
  
  private
  
  def set_profile_picture
    if self[:photo_url].empty?
      if self[:sex_id] == 1
        self[:photo_url] = "/img/signup_male.jpg"
      else
        self[:photo_url] = "/img/signup_female.png"
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :authenticate_user!, only: [:show]
  def show
    @branch = Branch.find_by_id(session[:branch_id])
    @order_lines = current_order.order_lines
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/commerce_helper.rb
module CommerceHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
	<%= form_for order_line, remote: true do |f| %>
		<div class="row">
			<div class="col-xs-8">
				<div class="media">
					<div class="media-left">
						<img class="media-object" src="<%= item.photo %>" alt="<%= item.name %>" width="100px" height="100px">
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= item.name %></h4>
						<%= item.description %>
						<%= f.text_field :observation, value: order_line.observation, class: "form-control" %>
					</div>
				</div>
			</div>
			<div class="col-xs-4">
			  
			    <h4 class="text-right">Precio unitario: <span style="color: green"><%= number_to_currency order_line.unit_price %></span></h4>
			    <div class="row">
			      <div class="col-xs-4">
			        <%= f.number_field :quantity, value: order_line.quantity.to_i, class: "form-control", min: 1 %>
			        <%= f.hidden_field :product_id, value: item.id %>
			      </div>
			      <div class="col-xs-8 text-right">
			        <div class="btn-group">
			          <%= f.submit "Actualizar", class: "btn btn-primary" %>
			          <%= link_to "Quitar", order_line, { data: { confirm: "¿Está seguro de quitar '#{order_line.item.name}' de su pedido?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
			        </div>
			      </div>
			    </div>
			    <h4 class="text-right">Sub-total: <span style="color: green"><%= number_to_currency order_line.total_price %></span></h4>
			 
			</div>
		</div>
	<% end %>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_line.nil? && @order_line.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_line.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_lines.nil? or @order_lines.size == 0 %>
  <p class="text-center">
    Todavía no has pedido nada. <%= link_to "Volvé a la carta", menu_path(session[:branch_id]) %> y prepará tu pedido.
  </p>
<% else %>
	<% @order_lines.each do |order_line| %>
		<%= render 'carts/cart_row', item: order_line.item, order_line: order_line, show_total: true %>
	<% end %>
	
	<p class="text-center">
	    <%= link_to "Quiero agregar más", menu_path(session[:branch_id]), class: "btn btn-primary" %>
	</p>
	
	<h2 class="text-center">
		Total: <span style="color: blue"><%= number_to_currency current_order.subtotal %></span>
	</h2>
	
	<div class="well">
		<div class="row">
			<%= form_for current_order do |f| %>
				<% if current_order.errors.any? %>
					<div id="error_explanation">
					  <h2><%= pluralize(current_order.errors.count, "error") %> prohibited this branch from being saved:</h2>
					
					  <% current_order.errors.full_messages.each do |message| %>
					    <div class="alert alert-danger" role="alert">
					    	<p><%= message %></p>
					    </div>
					  <% end %>
					</div>
				<% end %>
	
				<div class="col-xs-4 col-sm-4 col-md-4">
					<h3>Envío</h3><br />
					<p><strong>Usuario</strong></p>
					<p><%= current_order.user.first_name + " " + current_order.user.last_name %></p><br />
					<p><strong>Ciudad</strong></p> 
					<p><%= current_order.branch.city.name + " - " + current_order.branch.city.province.name + " - " + current_order.branch.city.province.country.name %></p>
					<br />
				</div>
			
				<div class="col-xs-8 col-sm-8 col-md-8">
				
					<div class="form-group">
				      <%= f.label "Calle" %>
				      <%= f.text_field :address, value: current_order.address, class: "form-control" %>
				    </div>
				    
				    <div class="form-group">
				      <%= f.label "Departamento (opcional)" %>
				      <%= f.text_field :apartment, value: current_order.apartment, class: "form-control" %>
				    </div>
				    
				    <div class="form-group">
				      <%= f.label "Teléfono" %>
				      <%= f.text_field :phone, value: current_order.phone, class: "form-control" %>
				    </div>
				    
				    <div class="form-group">
				      <%= f.label "Nota" %>
				      <%= f.text_field :observation, value: current_order.observation, class: "form-control" %>
				    </div>
				    
				    <div class="form-group">
				      <%= f.label "Pago con" %>
				      <%= f.text_field :cash, value: current_order.cash, class: "form-control" %>
				    </div>
					
					<div class="actions">
						<%= f.submit "¡Listo!", class: "btn btn-primary", data: { confirm: "¿Está seguro de enviar el pedido? ¿No olvidaste nada?" } %>
						<%= f.submit "Cancelar", class: "btn btn-danger", data: { confirm: "¿Está seguro de cancelar el pedido?" } %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/carts/show.html.erb
<%
	@tabs = Hash.new
	@tabs["orders"] = "active"
%>
<%= render layout: 'layouts/tabs_profile_branch', locals: {title: 'Pedido On-line'} {  } %>
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>